"""auto

Revision ID: f4bc0852bb9a
Revises: f60e6a92c60b
Create Date: 2026-06-05 17:35:06.713402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4bc0852bb9a'
down_revision = 'f60e6a92c60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_code', sa.String(length=64), nullable=False),
    sa.Column('routing_name', sa.String(length=256), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('revision', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('canvas_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routing_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routing_master_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routing_master_routing_code'), ['routing_code'], unique=False)

    op.create_table('routing_product_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.String(length=128), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['routing_id'], ['routing_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routing_product_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routing_product_assignments_product_id'), ['product_id'], unique=False)

    op.create_table('routing_steps_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.String(length=256), nullable=False),
    sa.Column('cycle_time', sa.Float(), nullable=True),
    sa.Column('operator_skill', sa.String(length=128), nullable=True),
    sa.Column('parallel', sa.Boolean(), nullable=True),
    sa.Column('qc_required', sa.Boolean(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('rework_allowed', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['routing_id'], ['routing_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wo_routing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('routing_code', sa.String(length=64), nullable=False),
    sa.Column('routing_revision', sa.String(length=16), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(length=128), nullable=True),
    sa.Column('step_name', sa.String(length=256), nullable=False),
    sa.Column('cycle_time', sa.Float(), nullable=True),
    sa.Column('qc_required', sa.Boolean(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('rework_allowed', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['routing_id'], ['routing_master.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('from_step', sa.Integer(), nullable=False),
    sa.Column('to_step', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_step'], ['routing_steps_v2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routing_id'], ['routing_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_step'], ['routing_steps_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_connections')
    op.drop_table('wo_routing_snapshots')
    op.drop_table('routing_steps_v2')
    with op.batch_alter_table('routing_product_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routing_product_assignments_product_id'))

    op.drop_table('routing_product_assignments')
    with op.batch_alter_table('routing_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routing_master_routing_code'))
        batch_op.drop_index(batch_op.f('ix_routing_master_product_id'))

    op.drop_table('routing_master')
    # ### end Alembic commands ###
