"""initial

Revision ID: f60e6a92c60b
Revises: 
Create Date: 2026-06-05 16:48:18.027053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60e6a92c60b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('component_part_number', sa.String(length=64), nullable=False),
    sa.Column('quantity_per_unit', sa.Float(), nullable=False),
    sa.Column('designator', sa.String(length=128), nullable=True),
    sa.Column('revision', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bom_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_items_part_number'), ['part_number'], unique=False)

    op.create_table('burn_in_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wo_id', sa.String(), nullable=False),
    sa.Column('chamber_id', sa.String(), nullable=True),
    sa.Column('planned_hours', sa.Float(), nullable=False),
    sa.Column('actual_hours', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calibration_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('certificate_number', sa.String(), nullable=True),
    sa.Column('certificate_path', sa.String(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('next_due_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('downtime_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('reason_category', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reported_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electronic_signatures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('signature_hash', sa.String(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('golden_boards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('limit_file_path', sa.String(), nullable=True),
    sa.Column('reference_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('inspection_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('operation_name', sa.String(), nullable=False),
    sa.Column('aql_level', sa.String(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('accept_limit', sa.Integer(), nullable=True),
    sa.Column('reject_limit', sa.Integer(), nullable=True),
    sa.Column('critical_checklist', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('log_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('parts_replaced', sa.JSON(), nullable=True),
    sa.Column('downtime_minutes', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.String(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_certifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('operation_code', sa.String(), nullable=False),
    sa.Column('certification_level', sa.String(), nullable=False),
    sa.Column('certified_at', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('certified_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('pm_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=True),
    sa.Column('last_completed_at', sa.Date(), nullable=True),
    sa.Column('due_at', sa.Date(), nullable=True),
    sa.Column('assigned_engineer', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shift_calendars',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('shift_name', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smt_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('solder_paste_lots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lot_number', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('quantity_g', sa.Float(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('floor_life_hours', sa.Float(), nullable=True),
    sa.Column('must_discard_by', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_number')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stencils',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stencil_code', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('print_count', sa.Integer(), nullable=True),
    sa.Column('print_count_limit', sa.Integer(), nullable=True),
    sa.Column('clean_cycle_interval', sa.Integer(), nullable=True),
    sa.Column('prints_since_last_clean', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stencil_code')
    )
    op.create_table('test_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('board_id', sa.String(), nullable=True),
    sa.Column('wo_id', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('test_type', sa.String(), nullable=False),
    sa.Column('overall_result', sa.String(), nullable=False),
    sa.Column('test_data', sa.JSON(), nullable=True),
    sa.Column('failure_codes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=64), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('plant_id', sa.String(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('esig_reason', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defect_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('wo_id', sa.String(), nullable=True),
    sa.Column('defect_code', sa.String(), nullable=False),
    sa.Column('defect_category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('is_repaired', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeder_reels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reel_id', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('quantity_initial', sa.Integer(), nullable=False),
    sa.Column('quantity_remaining', sa.Integer(), nullable=False),
    sa.Column('feeder_slot', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('wo_id', sa.String(), nullable=True),
    sa.Column('is_spliced', sa.Boolean(), nullable=True),
    sa.Column('splice_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reel_id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('quantity_on_hand', sa.Float(), nullable=True),
    sa.Column('quantity_reserved', sa.Float(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('is_rohs', sa.Boolean(), nullable=True),
    sa.Column('is_reach', sa.Boolean(), nullable=True),
    sa.Column('msd_level', sa.String(), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('floor_life_hours', sa.Float(), nullable=True),
    sa.Column('floor_life_start', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wo_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('kit_lines', sa.JSON(), nullable=True),
    sa.Column('picked_by', sa.String(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wo_id')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ncrs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('defect_id', sa.String(length=36), nullable=True),
    sa.Column('work_order_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('quarantine_location', sa.String(length=128), nullable=True),
    sa.Column('disposition_details', sa.Text(), nullable=True),
    sa.Column('dispositioned_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oee_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('smt_line_id', sa.String(), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_name', sa.String(), nullable=False),
    sa.Column('planned_production_time_min', sa.Float(), nullable=False),
    sa.Column('downtime_min', sa.Float(), nullable=True),
    sa.Column('speed_loss_min', sa.Float(), nullable=True),
    sa.Column('defect_loss_min', sa.Float(), nullable=True),
    sa.Column('availability', sa.Float(), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('oee', sa.Float(), nullable=True),
    sa.Column('units_planned', sa.Integer(), nullable=True),
    sa.Column('units_produced', sa.Integer(), nullable=True),
    sa.Column('units_defective', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['smt_line_id'], ['smt_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('routing_step', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=8), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pcb_panels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wo_id', sa.String(), nullable=False),
    sa.Column('panel_serial', sa.String(), nullable=False),
    sa.Column('board_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_serial')
    )
    op.create_table('ppap_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('wo_id', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_schedule',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('wo_id', sa.String(), nullable=False),
    sa.Column('smt_line_id', sa.String(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=False),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['smt_line_id'], ['smt_lines.id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('operation_sequence', sa.Integer(), nullable=False),
    sa.Column('operation_name', sa.String(length=128), nullable=False),
    sa.Column('workstation_type', sa.String(length=64), nullable=True),
    sa.Column('standard_cycle_time_sec', sa.Float(), nullable=False),
    sa.Column('station_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['station_name'], ['stations.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routing_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routing_steps_part_number'), ['part_number'], unique=False)

    op.create_table('serial_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plant_id', sa.String(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('capa_number', sa.String(), nullable=False),
    sa.Column('ncr_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('root_cause_analysis', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ncr_id'], ['ncrs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capa_number')
    )
    op.create_table('pcb_boards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('panel_id', sa.String(), nullable=True),
    sa.Column('wo_id', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['pcb_panels.id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('genealogy_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('board_id', sa.String(), nullable=False),
    sa.Column('wo_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('reel_id', sa.String(), nullable=True),
    sa.Column('feeder_slot', sa.String(), nullable=True),
    sa.Column('reference_designator', sa.String(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['pcb_boards.id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('board_id', sa.String(), nullable=False),
    sa.Column('wo_id', sa.String(), nullable=False),
    sa.Column('ncr_id', sa.String(), nullable=True),
    sa.Column('reference_designator', sa.String(), nullable=False),
    sa.Column('removed_part_number', sa.String(), nullable=False),
    sa.Column('removed_lot', sa.String(), nullable=True),
    sa.Column('installed_part_number', sa.String(), nullable=False),
    sa.Column('installed_lot', sa.String(), nullable=True),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('repaired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['pcb_boards.id'], ),
    sa.ForeignKeyConstraint(['ncr_id'], ['ncrs.id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('board_id', sa.String(), nullable=True),
    sa.Column('operation_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('process_parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['pcb_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_history')
    op.drop_table('repair_records')
    op.drop_table('genealogy_events')
    op.drop_table('pcb_boards')
    op.drop_table('capas')
    op.drop_table('alarms')
    op.drop_table('user_profiles')
    op.drop_table('serial_numbers')
    with op.batch_alter_table('routing_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routing_steps_part_number'))

    op.drop_table('routing_steps')
    op.drop_table('production_schedule')
    op.drop_table('ppap_records')
    op.drop_table('pcb_panels')
    op.drop_table('operation_transactions')
    op.drop_table('oee_snapshots')
    op.drop_table('ncrs')
    op.drop_table('machines')
    op.drop_table('kits')
    op.drop_table('inventory_items')
    op.drop_table('feeder_reels')
    op.drop_table('defect_records')
    op.drop_table('audit_log')
    op.drop_table('work_orders')
    op.drop_table('test_results')
    op.drop_table('stencils')
    op.drop_table('stations')
    op.drop_table('solder_paste_lots')
    op.drop_table('smt_lines')
    op.drop_table('shift_calendars')
    op.drop_table('roles')
    op.drop_table('pm_schedules')
    op.drop_table('plants')
    op.drop_table('operator_certifications')
    op.drop_table('maintenance_logs')
    op.drop_table('lines')
    op.drop_table('inventory_locations')
    op.drop_table('inspection_plans')
    op.drop_table('golden_boards')
    op.drop_table('electronic_signatures')
    op.drop_table('downtime_events')
    op.drop_table('calibration_records')
    op.drop_table('burn_in_sessions')
    with op.batch_alter_table('bom_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_items_part_number'))

    op.drop_table('bom_items')
    # ### end Alembic commands ###
